### PR TITLE
Populate v18.0.0

### PR DESCRIPTION
**Pull request by MementoRC**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by MementoRC** [comment]
@ofek This PR seems to be the correct one, it downloads and builds v18.0.0 - Hopefully, the windows build will work (it worked in the DBG PR)

**Comment by MementoRC** [comment]
@ofek This is the v18.0.0 PR track, the others were just to debug and test, sorry for the spam - We're getting close, all the dbg  passed, I added the tests to make sure the package builds correctly, since the `secp256k1` library is built prior to building `coincurve` for windows (somehow the setup.py on windows failed in my tryouts)

**Comment by MementoRC** [comment]
@carterbox Many packages depend upon v18.0.0, in particular `bip-utils` for which I have proposed a recipe. So, even though we agreed that the way v18.0.0 is packaged is not conda-forge abiding, I have proposed to add it as a one-off.
For that purpose, and if I understand enough of how the feedstock works, I am proposing to add a branch to the feedstock that will just have v18.0.0
ref: https://conda-forge.org/docs/maintainer/updating_pkgs.html#maintaining-several-versions
Do I understand this correctly?

**Review by ofek — APPROVED** [review]

**Comment by MementoRC** [comment]
@carterbox _difficilis concessus, venia facilis_

**Comment by ofek** [comment]
Do you mind explaining some of the issues that you worked out? I'm quite interested in learning about all of this stuff!

**Comment by MementoRC** [comment]
@ofek Well, it has to be premised with the fact that I likely do not know enough.
In any case, one of the issue is that for unknown reasons, the SOURCES.txt gets populated with fullpaths, which is not allowed. The only way I found to solve it was to add a `prune /*` command in the MANIFEST.in
Another is that coincurve installation process on windows, fails trying to access an admin path. But, later it seems that using --single and --record solved it (Note that, the final solution, is a built-up on things I thought were needed as I debugged, but that have not been removed once it worked)
So, building the `secp256k1` lib separately was mainly introduced because i had a hard time telling `setup.py` how to find the unix commands on the conda build environment. I spent several months working on it and I don't remember the details, I simply looked at old commits and pulled them into this one, with faith rather than knowledge

So this PR is likely a convoluted one.

For `coincurve`, I think one update should be to move to the CMkae-based `secp256k1` build, I worked on such PR, but somehow had difficulties, but since then I suggested some changes to SECP256K1 and it may work better now
The advantage of the conda packaging as compared to the PYPI is that `secp256k1` can be a standalone conda package that tracks the official repo with very minimal patching, so the `libsecp256k1-py-bindings` becomes itself a simple as just the CFFI wrap-around, then `coincurve` could actually become a `noarch` off ofthe bindings.

But then, you would not have a PYPI packaging solution

All in all, I think the current set is optimal. `coincurve` remains a standalone package for PYPI, while providing the required building-block approach for conda.

**Comment by MementoRC** [comment]
@ofek @carterbox v18.0.0 is live \o/:
image

**Comment by carterbox** [comment]
Yes, you can maintain multiple versions of a package on a feedstock by having a separate channel for each version. For example, the qt-main-feedstock has a 5.x branch and a 6.x branch.

However, this v18.0.0 branch/build does not comply with our channel policies regarding static linking and licensing. This was the entire reason for working with @ofek to create a new release of coincurve. If you needed the v18.x API for your other packages, you should have submitted a PR to coincurve that wasn't API breaking (one that only updated the build system and used the same version of libsecp256k1) instead of one that caused the creation of a new v19.x API that now won't be used because as you have mentioned, most of your packages require v18.x.

If you don't want to comply with our policies regarding licensing and linking. You are free to create your own conda channel.

**Comment by MementoRC** [comment]
@carterbox My apologies. I saw in the manual that there is a mean of retiring build, I will look into it and try to correct this mistake. I do intend to abide by the policy, I do appreciate all the help that you provided, as well as the existence of conda-forge. I also have a channel where I had published a few of these recipes

My faulty understanding of our discussion was that the policy would not allow a live recipe, I thought that a back-porting of a one-time build part of the recipe would be acceptable.

I hope you will allow the benefit of the doubt, as well as understand my eagerness to finally have things "working" for all those recipes that I created a few months ago and forgive this lapse of judgement

Sincerely

**Comment by MementoRC** [comment]
@carterbox You hint at a solution, but I do not understand it: `you should have submitted a PR to coincurve that wasn't API breaking` Do you mean a PR to the `coincurve-feedstock` that would download the `commit`-based reference to SECP256K1 un-released version and build v18.0.0 the same way as v19.x API? That is:
   - Update `libsecp256k1-feedstock` with a vpre-0.1.0 version
      - This may entail creating a new build system for that version, which did not use CMake
   - Use that version in `coincurve-feedstock` v18.0.0

Did I understand your suggestion correctly?

If you meant ofek's `coincurve`, this would still not be useful since ofek would need to up-version his release to incorporate my PR

Thank you

**Comment by carterbox** [comment]
>  that the policy would not allow a live recipe

What is a "live recipe"?

> @carterbox You hint at a solution, but I do not understand it: you should have submitted a PR to coincurve that wasn't API breaking

Are coincurve v18 and v19 API compatible? If so, this discussion is moot, and you didn't need to build coincurve v18 in this feedstock. `pip check` will report an error for downstream packages, but that's fine.

> Update libsecp256k1-feedstock with a vpre-0.1.0 version

Are you sure that a pre-release version is necessary?

Is there not a stable release of libsecp256k1 that is API compatible with the commit referenced in coincurve 18.0.0?

https://github.com/ofek/coincurve/blob/v18.0.0/setup.py -> https://github.com/bitcoin-core/secp256k1/commits/ddf2b2910eb19032f8dd657c66735115ae24bfba -> November 16, 2022 -> https://github.com/bitcoin-core/secp256k1/commits/v0.2.0  

Could you please try compiling coincurve v18.0.0 using libsecp256k1 v0.2.0? It looks like the [changes between ddf2b2910eb19032f8dd657c66735115ae24bfba and v0.2.0](https://github.com/bitcoin-core/secp256k1/compare/ddf2b2910eb19032f8dd657c66735115ae24bfba..v0.2.0) are minimal as far as the API is concerned (the headers in /include). As far as I can tell, the only changes to the headers are backwards compatible.

If that works, you can build coincurve v18.0.0 against libsecp256k1 v0.2.0. If you need to carry patches in this feedstock which modify coincurve's `setup.py` so that it dynamically links to libsecp256k1 v0.2.0, that's fine.

**Comment by MementoRC** [comment]
@carterbox Thank you for the suggestions. I had a few ill-conceived notions, such as 'live recipe' meaning the recipe that tracks the latest release and defines how future releases will be built, but I realize that is not a thing. Also, I saw the pragmatic effect of the v18, 10x the resource of v19!

Also, I thought I could not change the definition of ofek's v18.0.0, but you are correct, I should simply pick the oldest release past `dd...` commit. In fact, @ofek could also release a v18.0.1/0.2.0 if we really want to remain historically consistent. That would work as most packages only require `<19`

I will work on your proposal and make a PR to both this feedstock and the libsecp256k1 ... and I will not push any branch until your review and approval - For now, I seem to have broken `coincurve` on windows, so I need to work on that

Thank you

**Pull request merged**
